#!/bin/sh
# File generated by ocamlbuild

cd /home/isildur/Documents/Compiler/Assigments/project2_1

rm -f assert.cmi
rm -f assert.cmo
# Also clean the script itself
rm -f /home/isildur/Documents/Compiler/Assigments/project2_1/_build/sanitize.sh
